### Image upload
# Example return: {
#  "image_id": "nfces/nfce-1754662395-MjAyNS",
#  "message": "File uploaded successfully"
# }
POST http://localhost:8080/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="nota-test-1.png"
Content-Type: image/png

< ./nfces/nota-test-2.png
--boundary--


# nfces/nfce-1754503579-MjAyNS


### Scan with genai
POST http://localhost:8080/scan/ocr
Content-Type: application/json

{
  "image_id": "nfces/nfce-1754503579-MjAyNS"
}